---
- include_vars: app_vars.yml
  tags: always

- include_vars: ../traefik/vars/traefik_vars.yml
  tags: always

- include_vars: ../keycloak/vars/keycloak_vars.yml
  tags: always


# - name: debug vars
#   ansible.builtin.debug:
#     var: people
#   tags: debug

- name: Setup base for people
  tags:
    - people.setup
  import_tasks:
    file: setup.yml

- name: Whoami server for debugging
  tags:
    - never
    - people.run.whoami
  import_tasks:
    file: run_whoami.yml

- name: Source Code to Docker Image
  tags:
    - people.src
  import_tasks:
    file: src.yml

- name: Dev only source code stuff
  tags:
    - never
    - people.src.patch
    - people.db.reseed
  include_tasks:
    file: dev.yml
  when: people.env == "development"

- name: Mariadb
  tags:
    - people.run
    - people.run.db
  import_tasks:
    file: run_mariadb.yml
  when: SELECT_DB == 'local_mariadb'

- name: Redis Cache Server
  tags:
    - people.run
    - people.run.redis
  import_tasks:
    file: run_redis.yml
  when: SELECT_CACHE == 'local_redis'

- name: People
  tags:
    - people.run
    - people.run.app
  import_tasks:
    file: run.yml

- name: Configuration
  tags:
    - people.config
  import_tasks:
    file: config.yml


- name: People admin
  tags:
    - never
  import_tasks:
    file: admin.yml
