---

- name: Ensure system subscription to RHEL shit
  community.general.redhat_subscription:
    state: present
    username: "{{ rh_credentials.login }}"
    password: "{{ rh_credentials.password }}"
    auto_attach: true
  tags:
    - rhelshit

- name: Ensure podman related packages are present
  ansible.builtin.package:
    name: container-tools
    state: present
  tags:
    - system.install.podman

- name: Ensure essential packages for administration
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  tags:
    - system.install.admin
  when: RUNENV != 'prod'
  with_items:
    - bind-utils
    - net-tools
    - telnet

- name: Ensure essential packages for deployment
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  tags:
    - system.install.app
  with_items:
    - git
